name: Build f2f

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ubuntu:20.04

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        export DEBIAN_FRONTEND=noninteractive
        ln -fs /usr/share/zoneinfo/UTC /etc/localtime
        dpkg --add-architecture i386
        apt update
        apt install -y --no-install-recommends \
          g++-multilib gcc-multilib \
          libstdc++6:i386 \
          libsqlite3-dev libsqlite3-dev:i386 \
          libcurl4-openssl-dev libcurl4-openssl-dev:i386 \
          libssl-dev libssl-dev:i386 \
          python3-pip ninja-build pkg-config tzdata
        dpkg-reconfigure -f noninteractive tzdata
        pip3 install meson

    - name: Build
      run: |
        meson setup build --buildtype=release \
          -Dcompile_sqlite=true \
          -Dcompile_curl=true \
          -Dcompile_ssl=true \
          -Denable_unsafe=true \
          -Dairjumps=true
        ninja -C build

    - name: Upload .so
      uses: actions/upload-artifact@v4
      with:
        name: f2f
        path: build/f2f.so
