name: Build f2f

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ubuntu:20.04

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        dpkg --add-architecture i386
        apt update
        apt install -y g++-multilib python3-pip ninja-build pkg-config
        pip3 install meson

    - name: Build
      run: |
        meson setup build --buildtype=release -Dcompile_sqlite=false -Dcompile_curl=false -Dcompile_ssl=false
        ninja -C build

    - name: Upload .so
      uses: actions/upload-artifact@v4
      with:
        name: f2f
        path: build/f2f.so
